apply plugin: 'org.springframework.boot'
dependencies {
    implementation project(":api-rest")
    implementation project(":security-provider")
    implementation project(":aws-provider")
    implementation project(":usecase")
    implementation project(":model")
    implementation project(":security")
    implementation project(":jpa-repository")
    implementation project(":core-service-provider")
    implementation ("org.springframework.boot:spring-boot-starter")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
}
